logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092

eureka:
  client:
    enabled: false
