spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      # We should really use validate
      ddl-auto: update
  sql:
    init:
      mode: always
