spring:
  application:
    name: document_store
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  profiles:
    active:
      - dev
      - no-security
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:1MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:10MB}
